### ISSUE TITLE
Multiple Modules not shown in Beautiful Tucan

### ISSUE THREAD

**Issue by DecayMehls** [d120/beautiful-tucan#11]
Consider those two Screenshots. Multiple Modules which are present in Tucan get not picked up by the making Scripts of Beautiful Tucan.
Only checked the Category "Software Systeme und formale Grundlagen" probably more that also missing.
Cant figure out why because i cant see any differences between the missing ones and the ones who show up.
Screenshots taken from my own instance of beautiful tucan and tucan.
![TUCAN_WBA_ITS](https://user-images.githubusercontent.com/15329053/66910996-f2313e80-f00f-11e9-8703-56cde3ed46f5.png)
![BT_WBA_ITS](https://user-images.githubusercontent.com/15329053/66911042-083eff00-f010-11e9-81c2-a117788d7b70.png)

**Comment by miterion** [comment]
Inferno seems to be out of date currently. The new system is located under imap.dekanat.informatik.tu-darmstadt.de and works exactly like the old version under inferno....

I fixed the url on master and works for me (and in the deployed version). Do you want to check?

**Comment by drcicero** [comment]
Are you sure? First I can't access http://imap.dekanat.informatik.tu-darmstadt.de "Unable to connect: Firefox can’t establish a connection to the server at imap.dekanat.informatik.tu-darmstadt.de"; and second I am pretty sure imap is the email protocol, so it must be an error if inferno is available behind that url.

**Comment by drcicero** [comment]
Nice to see someone checking the data!

If you look into the "cache/*.json" files, you will probably find that the course was downloaded, its just not shown.

That is, because according to inferno this course is not part of regulation bachelor or master 2015: http://inferno.dekanat.informatik.tu-darmstadt.de/pp/plans/modules/20-00-0635 . I would be interested in whether you can see these courses also under "Tucan > Veranstaltung > Anmeldung > ...". I cannot check that anymore as i am no longer in a bachelor. It seems like it is selectable in master so I guess the inferno data must be wrong here.

There are courses, modules and regulations. They have the following form:
  regulation="B.Sc. Informatik (2015)",
  module=03-03-1356, 03-03-1332, 03-03-1363,
  course=03-03-1356-vl, 03-03-1356-ue.

A module can have multiple courses, and a course can be in multiple modules. Tucan-VV lists courses of this semester with their dates and associated modules but not credits or regulations. Inferno lists regulations with associated modules and credits but not courses. And more: the Tucan-VV does not always show the same courses as you can find under "Tucan > Veranstaltung > Anmeldung"...

**Comment by miterion** [comment]
@drcicero I am really sure. It only works from the university network and they chose the name as a joke.

**Comment by drcicero** [comment]
err... (what is the joke about, and) why is the old website still online if there is a new one...

**Comment by DecayMehls** [comment]
Why isn't the new link imap.dekanat on the FB Informatik website?
As you can see here :[FB 20 Prüfungen](https://www.informatik.tu-darmstadt.de/studium_fb20/im_studium/studienbuero/pruefungen/index.de.jsp) its still the old one.

And their is a big difference in the data you already mentioned!

**Comment by miterion** [comment]
I will ask in the next days what the future situation will be.

**Comment by miterion** [comment]
> I will ask in the next days what the future situation will be.

imap is a new instance of the inferno software, which runs on a new host. While it is still in testing we can expect that it will be the default in the future (there will be redirects from inferno though).

The missing modules in inferno are already reported to the maintainers, though they do not have the time to fix this. I would suggest to leave the imap.dekanat... URL in the repo and add some notice to the readme that the script can only be executed from the university network.
